### ISSUE TITLE
Flexbox Froggy

### ISSUE THREAD

**Issue by jasonliao** [SelinaYu/Step-by-Step#1]
[Flexbox Froggy](http://flexboxfroggy.com/?utm_source=html5weekly&utm_medium=email) is a game for learning CSS Flexbox.

Use your code to guide the froggy to the lilypad and have fun! :)

**Comment by SelinaYu** [comment]
Get it ! It's interesting and helps me remember their property!Thank you!

**Comment by jasonliao** [comment]
Today I found out a blog post called [`flex-grow` is weird. Or is it?](https://css-tricks.com/flex-grow-is-weird/), it's well explain property `flex-grow` in flex layout, check it out! :)
